spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/connect"
  jpa:
    hibernate.ddl-auto: "create-drop"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: "true"
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: google-client-id
#            clientSecret: google-client-secret

#server:
#  error:
#    include-message: always
#logging:
#  level:
#    org.springframework.security: trace




